rfam_analytics:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '/Users/christianpohlmann/Coding/sql_to_duckdb_pipeline.duckdb'  # Updated path to the newly created database
      threads: 4 