rfam_analytics:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '/Users/christianpohlmann/Coding/rfam_analytics/dev.duckdb'  # Path to our new database
      schema: main  # Explicitly specify the schema
      threads: 4 